/**
 * blockchain.js  — EVM (Hardhat/Ethereum) contract interaction service
 *
 * Ported from farm-chain-chronicles-main/src/hooks/use-ethereum.ts and adapted
 * for the FarmChain v2 backend. Provides:
 *
 *  - connectMetaMask()      : Connect to user's MetaMask wallet on the local Hardhat network
 *  - connectDevWallet()     : Connect using Hardhat Account #0 private key (dev mode only!)
 *  - getContracts(signer)   : Return ethers.Contract instances for Registry + ProduceBatch
 *  - getRegistryContract()  : Read-only Registry contract
 *  - getBatchContract()     : Read-only ProduceBatch contract
 *
 * Chain: Hardhat localhost — chainId 31337, RPC http://127.0.0.1:8545
 *
 * Import:
 *   import { connectMetaMask, getContracts, getBatchContract } from '../services/blockchain';
 */

import { ethers } from 'ethers';

// ── Contract metadata (auto-generated by deploy-chronicle.js) ────────────────
// If this import fails, run: cd blockchain && npx hardhat run scripts/deploy-chronicle.js --network localhost
let chronicleContracts;
try {
  // Dynamic import so the app doesn't crash if contracts haven't been deployed yet
  const mod = await import('./chronicle-contracts.json', { assert: { type: 'json' } });
  chronicleContracts = mod.default;
} catch {
  chronicleContracts = null;
  console.warn('[blockchain.js] chronicle-contracts.json not found. Run deploy-chronicle.js first.');
}

const CHAIN_ID    = 31337; // Hardhat
const RPC_URL     = import.meta.env.VITE_RPC_URL || 'http://127.0.0.1:8545';

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

function getProvider() {
  return new ethers.JsonRpcProvider(RPC_URL);
}

/**
 * Switch MetaMask to the Hardhat local network.
 * Prompts user to add the network if it isn't already configured.
 */
async function ensureHardhatNetwork() {
  const chainIdHex = '0x' + CHAIN_ID.toString(16); // 0x7A69

  try {
    await window.ethereum.request({
      method: 'wallet_switchEthereumChain',
      params: [{ chainId: chainIdHex }],
    });
  } catch (switchErr) {
    if (switchErr.code === 4902) {
      await window.ethereum.request({
        method: 'wallet_addEthereumChain',
        params: [{
          chainId: chainIdHex,
          chainName: 'FarmChain Localnet',
          rpcUrls: [RPC_URL, 'http://localhost:8545'],
          nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
        }],
      });
    } else if (switchErr.code !== 4001) {
      // 4001 = user rejected — propagate everything else
      throw switchErr;
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Connect to the user's MetaMask wallet and switch to the Hardhat network.
 * @returns {{ account: string, signer: ethers.Signer }}
 */
export async function connectMetaMask() {
  if (!window.ethereum) {
    throw new Error('MetaMask (or compatible EVM wallet) not detected. Please install it.');
  }

  await ensureHardhatNetwork();

  const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
  if (!accounts || accounts.length === 0) throw new Error('No accounts returned');

  const provider = new ethers.BrowserProvider(window.ethereum);
  const signer   = await provider.getSigner();

  return { account: accounts[0], signer };
}

/**
 * Connect using Hardhat Account #0 private key — FOR DEVELOPMENT ONLY.
 * Never expose this in production builds.
 * @returns {{ account: string, signer: ethers.Signer }}
 */
export async function connectDevWallet() {
  const provider  = new ethers.JsonRpcProvider(RPC_URL);
  // Hardhat default Account #0 key — safe because devnet coins have no real value
  const devSigner = new ethers.Wallet(
    '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
    provider
  );
  return { account: devSigner.address, signer: devSigner };
}

/**
 * Return live ethers.Contract instances connected to the given signer.
 * Requires chronicle-contracts.json to exist (generated by deploy-chronicle.js).
 *
 * @param {ethers.Signer} signer
 * @returns {{ registry: ethers.Contract, produceBatch: ethers.Contract }}
 */
export function getContracts(signer) {
  if (!chronicleContracts) {
    throw new Error('Chronicle contracts not deployed. Run: npx hardhat run scripts/deploy-chronicle.js --network localhost');
  }

  return {
    registry:     new ethers.Contract(chronicleContracts.FarmChainRegistry, chronicleContracts.RegistryABI, signer),
    produceBatch: new ethers.Contract(chronicleContracts.ProduceBatch,      chronicleContracts.BatchABI,    signer),
  };
}

/**
 * Read-only Registry contract (no signer required).
 * @returns {ethers.Contract}
 */
export function getRegistryContract() {
  if (!chronicleContracts) return null;
  return new ethers.Contract(chronicleContracts.FarmChainRegistry, chronicleContracts.RegistryABI, getProvider());
}

/**
 * Read-only ProduceBatch contract (no signer required).
 * @returns {ethers.Contract}
 */
export function getBatchContract() {
  if (!chronicleContracts) return null;
  return new ethers.Contract(chronicleContracts.ProduceBatch, chronicleContracts.BatchABI, getProvider());
}

/**
 * Return deployed contract addresses (useful for block-explorer links).
 */
export function getContractAddresses() {
  return {
    registry:     chronicleContracts?.FarmChainRegistry ?? null,
    produceBatch: chronicleContracts?.ProduceBatch      ?? null,
    chainId:      CHAIN_ID,
    rpcUrl:       RPC_URL,
  };
}

/**
 * Convenience: build Hardhat local block-explorer URL for a transaction.
 * (Use https://sepolia.etherscan.io/tx/... for testnets)
 */
export function getTxUrl(txHash) {
  // Hardhat has no explorer; format a generic link for reference
  return `http://localhost:8545/tx/${txHash}`;
}

export default {
  connectMetaMask,
  connectDevWallet,
  getContracts,
  getRegistryContract,
  getBatchContract,
  getContractAddresses,
  getTxUrl,
};
